resolver: lts-11.13
flags: {}
arch: x86_64
extra-package-dbs: []
require-stack-version: ">=1.6"

ghc-options:
   "$locals": -fhide-source-paths

packages:
- '.'
- location:
    git: https://github.com/adjoint-io/pedersen-commitment.git
    commit: 23f73e6a7b535c8584ce44838c6c7674143ab7cd
  extra-dep: true

- location:
    git: https://github.com/adjoint-io/datetime.git
    commit: c9165f741634908b1913f0b93b66b7a06a2c298a
  extra-dep: true

- location:
    git: https://github.com/adjoint-io/merkle-tree.git
    commit: a942ee26f56d24473757af5d1bda48c39b2ebd44
  extra-dep: true

- location:
    git: https://github.com/sdiehl/repline.git
    commit: 3474422d974cb264aa96fcfaae31e1969b134815
  extra-dep: true

- location:
    git: https://github.com/adjoint-io/network-transport-tcp-tls.git 
    commit: db8e2d4ed677e136fb1b7a2666e9a12511ae5d24
  extra-dep: true

extra-deps:
- base58-bytestring-0.1.0
- hexpat-pickle-0.6
- postgres-tmp-0.2.0
- distributed-process-async-0.2.6
- distributed-process-client-server-0.2.5.1
- distributed-process-extras-0.3.5
- distributed-process-supervisor-0.2.1

docker:
  enable: false
  auto-pull: true

image:
  container:
    name: uplink
    base: fpco/stack-run
    # Add files ( relative to build dir )
    add:
      config: /config
