apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.kubernetes.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: uplink
  name: uplink
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: uplink
    spec:
      containers:
      - command:
        - bash
        - -c
        - sleep 7 && yes n | uplink chain init -c config/node.config.local.docker
        image: eu.gcr.io/uplink-test-cluster-174313/uplink:latest
        name: uplink
        ports:
        - containerPort: 8545
        resources: {}
      restartPolicy: Always
status: {}
