apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: uplink
  name: uplink
spec:
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  selector:
    io.kompose.service: uplink
status:
  loadBalancer: {}
