apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: uplink-explorer
  name: uplink-explorer-expose
spec:
  loadBalancerIP: 35.187.35.192
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: uplink-explorer
  type: LoadBalancer
status:
  loadBalancer: {}
