apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: validator-1
  name: validator-1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: validator-1
    spec:
      containers:
      - command:
        - bash
        - -c
        - sleep 5 && uplink chain  -c config/node.config.local.docker
          -k config/validators/auth1/key
        image: eu.gcr.io/uplink-test-cluster-174313/uplink:24ef8dc78ce9bdec090228eeebd026b9e2e52e92
        name: validator-1
        resources: {}
      restartPolicy: Always
status: {}
